webclient:
  rootUrl: http://localhost:8080

spring:
  security:
    oauth2:
      client:
        provider:
          springauth:
            token-uri: http://localhost:9000/oauth2/token
        registration:
          springauth:
            client-name: springauth
            client-id: messaging-client
            client-secret: secret
            scope[0]: message.read
            scope[1]: message.write
            authorization-grant-type: client_credentials
            provider: springauth
